**Numpy Introduction**

This is for 1 d (1 dimensional array)

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built. Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.

The key features of numpy are:

ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient. There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
<lr>Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.<lr>
<lr>Vectorization: enables numeric operations on ndarrays.<lr>
<lr>Input/Output: simplifies reading and writing of data from/to file.<lr>

In [1]:
import numpy as np
x = np.array([3, 33, 333]) 
print(x)


[  3  33 333]


In [1]:
import numpy as np
y = np.array([[3, 33, 333],[2,22,333]]) 
print(y)

[[  3  33 333]
 [  2  22 333]]


**Indexing** [row,column]

In [2]:
y[1,1]

22

In [3]:
y[:,1]

array([33, 22])

In [5]:
y.shape

(2, 3)

In [8]:
print(y[0,1]) # Slicing 
print(y[0]) # indexing
#print(y[:,1])

33
[  3  33 333]


In [2]:
import numpy as np
z=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(z)
print("the shape",z.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
the shape (3, 5)


In [3]:
z[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [4]:
z[0]

array([1, 2, 3, 4, 5])

In [5]:
z[0,1]

2

In [17]:
z[:,0]

array([ 1,  6, 11])

In [12]:
ex1=np.zeros([2,3])
print(ex1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
ex2=np.ones([3,3])
print(ex2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
import numpy as np
ex3=np.full([3,3],9)
print(ex3)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [20]:
ex4=np.eye(3,3)
print(ex4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
x1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
x2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [24]:
print(x1)
print("")
print(x2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
print("The value of x1 : ")
print(x1)
print("The value of x2 : ")
print(x2)

The value of x1 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The value of x2 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
x3=x1+x2
print(x3)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [30]:
x3=np.add(x1,x2)
print(x3)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [31]:
x3=x1-x2

In [32]:
x3=np.subtract(x1,x2)

In [40]:
ex5 = np.random.random((2,2))
print(ex5)    

[[0.95046868 0.53441754]
 [0.03777007 0.35378259]]


In [10]:
ex6=np.arange(0,15)
print(ex6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [43]:
import numpy as np
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [44]:
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [45]:
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

In [46]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [49]:
an_array[filter]

array([ 21, 122,  31, 132])

In [52]:
mean_val=np.random.random((2,3))
print(mean_val)

[[0.71687579 0.52102203 0.14209891]
 [0.73155426 0.98389101 0.96260753]]


In [53]:
np.mean(mean_val)

0.6763415884732188

In [55]:
print(mean_val.mean(axis = 1)) # axis =1 i s for rows 

[0.45999891 0.89268427]


In [56]:
print(mean_val.mean(axis = 0)) # axis o is for col

[0.72421502 0.75245652 0.55235322]


In [57]:
print(mean_val.sum())

4.0580495308393125


In [60]:
print(np.median(mean_val, axis = 0)) 

[0.72421502 0.75245652 0.55235322]


In [61]:
x1 = np.array([1,2,1,4,2,1,4,2])

print(np.unique(x1))

[1 2 4]


In [67]:
mean_val.sort()
print(mean_val)

[[0.14209891 0.52102203 0.71687579]
 [0.73155426 0.96260753 0.98389101]]
